### ISSUE TITLE
Not able to install the library Cause: com/android/build/api/extension/AndroidComponentsExtension

### ISSUE THREAD

**Issue by BhaveshL94** [google/secrets-gradle-plugin#33]

**Comment by BhaveshL94** [comment]
![image](https://user-images.githubusercontent.com/49588631/124627989-a71f2500-de9d-11eb-8a44-30e9b421edc1.png)
![image](https://user-images.githubusercontent.com/49588631/124628017-b00ff680-de9d-11eb-9eff-a48fe56bc274.png)

**Comment by arriolac** [comment]
Hi @BhaveshL94, you are receiving that error because the version of AGP you are using is 4.1.3 whereas the latest version of this plugin requires 4.2.x. To fix this, consider bumping your AGP version to the [latest version](https://developer.android.com/studio/releases/gradle-plugin#4-2-0) (4.2.0) or use an older version of this plugin (1.2.0).

Relates to #25.

**Comment by arriolac** [comment]
Closing this. Please reopen / comment if you are still encountering this issue.
